### ISSUE TITLE
135 please.

### ISSUE THREAD

**Issue by rylid-umil** [mindustry-antigrief/mindustry-client#102]
i cant use my mod in 136 because standard bullet types got removed. make a ver for 135 please

**Comment by buthed010203** [comment]
135 is ancient by now, get your mods updated or build a 135 version manually. Afaik this was the first 135 commit https://github.com/mindustry-antigrief/mindustry-client/commit/f9039df831f69a17cd7b5eef58da0cd6ec98db88
