### ISSUE TITLE
中国玩家无法在服务器上投票以及无法下载声音

### ISSUE THREAD

**Issue by YinHe0708** [mindustry-antigrief/mindustry-client#107]
因/投票 提出 UID发出去又成了/votekick #ID码，希望投票指令自动转换可以关闭
![1N@Q Y7V {R}ZSD(%@HWZT4](https://user-images.githubusercontent.com/99188321/194194622-d2165eeb-e123-4fd4-baa5-641a32a3a6b3.png)
![CH)9F BBTP~`SK~2X9OAE{0](https://user-images.githubusercontent.com/99188321/194194631-0654c8ee-455b-46bd-907e-1be7c2fee9dd.png)

**Comment by buthed010203** [comment]
I don't speak chinese...

**Comment by buthed010203** [comment]
How are you downloading the client if you cant access github?

On top of that, the kick using player ids is a vanilla feature now.
