### ISSUE TITLE
where my translated text

### ISSUE THREAD

**Issue by Linnnnnna** [mindustry-antigrief/mindustry-client#120]
### What happened?

![H2NFT8R6Q W03~R6 C71_SJ](https://user-images.githubusercontent.com/63439268/201452012-fa35dcc1-a717-4dd7-a9ac-31659f25d643.png)

**Comment by buthed010203** [comment]
Does it happen if you reload the game?

**Comment by Linnnnnna** [comment]
> 
It doesn't even exist in the source text
https://github.com/mindustry-antigrief/mindustry-client/blob/v7/core/assets/bundles/bundle_zh_CN.properties

**Comment by Linnnnnna** [comment]
> Does it happen if you reload the game?

It doesn't even exist in the source text
https://github.com/mindustry-antigrief/mindustry-client/blob/v7/core/assets/bundles/bundle_zh_CN.properties

**Comment by buthed010203** [comment]
Weird... I grabbed it from the last commit you made
