### ISSUE TITLE
[Suggestion] Add sea and air paths

### ISSUE THREAD

**Issue by Robotsrule4545** [mindustry-antigrief/mindustry-client#124]
When I go to campaign, the flares take a different route, and it doesn't show... Also, when it's an only air sector, there is no path.

**Comment by buthed010203** [comment]
Imagine suggesting on github

**Comment by Linnnnnna** [comment]
> 

How about add circleassist distance

**Comment by Linnnnnna** [comment]
> Imagine suggesting on github

How about add circleassist distance

**Comment by Linnnnnna** [comment]
![C)9EUR9Y$SGU3U ~L8LS5B](https://user-images.githubusercontent.com/63439268/203273101-d042e48b-2bb8-41e1-8d66-8a12291ecf69.gif)

**Comment by buthed010203** [comment]
These have been partially implemented for a while now, I'll finish them up eventually
