### ISSUE TITLE
[Suggestion] Better minimap

### ISSUE THREAD

**Issue by Nikoichu** [mindustry-antigrief/mindustry-client#135]
I think the minimap in mindustry could use some improvements, so why not through this client?
Here are a bunch of suggestions that will make the minimap better:

-Resizable minimap:
Basically add a little arrow in the corner of the minimap that can be mouse-dragged to resize the minimap in both directions independently (so it doesn't have to be a square). The current minimap is too... mini, way too small compared to the rest of the UI.

-Option to lock the minimap ratio to the current map ratio
So if the map is 400 tiles long and 300 wide, the minimap will be locked in a 4:3 ratio.

-Button (or hotkey) to reset minimap scale to 1:1
This will automatically scale and zoom the minimap, so one tile on the map corresponds perfectly to one pixel on the minimap.

-Preview window of where your camera is on the minimap
A basic feature present in most other RTS games, basically an outline of what your camera is looking at on the minimap.
Also option to move the camera by left-clicking on the minimap and to order units to go to a location with right-click (when in command mode). The current behavior of opening the fullscreen minimap can be rebound to middle-click or users can just use the "M" key.

-Control for unit previews on the minimap
Options to outline, scale or color shift the units on the minimap, so they don't blend with the buildings.
Maybe also specific options for color-shifting the player-controlled unit and the unit selection in unit control mode.

-Attack Alerts on the minimap
Again, a common RTS feature. When a core is attacked (displaying the "Core under attack!" message), there should be a red target mark that shows where the core in question is on the minimap.
Optionally, attack alerts could be shown for any off-screen building/unit that is being attacked when neither it nor other units/buildings in the vicinity (in a radius of 40 blocks) has sent an attack alert in the past 20 seconds (to prevent spam)

**Comment by Leo-MathGuy** [comment]
Rusted warfare be like:

**Comment by bend-n** [comment]
The minimap already is resizable, you can scroll and drag it

**Comment by Nikoichu** [comment]
@bend-n I meant resizable minimap frame, so it takes more (or less) area on the screen. Like you can resize windows on your desktop basically.

**Comment by buthed010203** [comment]
Probably won't get around to adding this, I hate doing ui stuff.
