### ISSUE TITLE
instant build/deconstruct sandbox mode

### ISSUE THREAD

**Issue by rylid-umil** [mindustry-antigrief/mindustry-client#137]
i wanna bring back the feature where you could build, deconstruct almost instantly while in sandbox mode, it was in the okld version but its gone now, if you cant bring it back, explain why you cant bring it back and why you removed it in the first place.

**Comment by buthed010203** [comment]
This has been planned since I removed it. I ended up removing it as I was too lazy to merge conflicts as I had already merged >100 just for the v7 update

**Comment by rylid-umil** [comment]
oh so its planned to be added later?

**Comment by buthed010203** [comment]
Yep
