### ISSUE TITLE
[SUGGESTION] default poly/mega behaviour ?

### ISSUE THREAD

**Issue by DaveInDev** [mindustry-antigrief/mindustry-client#144]
Hi, when creating a poly/mega, it automatically switch to "build" mode. When you are in a fight, it means that the poly/mega will automatically rush on the "war front", trying to rebuild destroyed buildings, and most of the time, it results in a suicide because the unit flies in front of an enemy turret.

So it would be nice to have an option to choose the default behaviour of a poly/mega (stop, repair, rebuild, assist player).

It's the same problem when you have the control of a poly/mega, and take control of a turret : the poly/mega is free and rushes again into dangerous places... This option should take care of this situation too.

**Comment by dmgnr** [comment]
This should the main game feature

**Comment by buthed010203** [comment]
Added to vanilla
