### ISSUE TITLE
Game crashes on random, idk [Bug] 

### ISSUE THREAD

**Issue by eclipse1408** [mindustry-antigrief/mindustry-client#148]
### What happened?

what happens:
mindustry crashes on random. first, at some random moment(both campaign and multiplayer), the game freezes, but the music remains for around a couple of minutes. on pressing alt-tab, the game goes unresponsive, (as in a window pops up).
Sometimes the window says, "OpenJDK Platform has stopped working", and sometimes it says Mindustry.exe instead.
Platform: *The type of device you were playing on - Windows
Build: *The build number under the title in the main menu- Build 142

[saves.zip](https://github.com/Anuken/Mindustry/files/10819332/saves.zip)

last log:
[I] [GL] Version: OpenGL 4.3.0 / Intel / Intel(R) HD Graphics 4400
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 1.4 GB
[I] [CLIENT] Version: 311ece2, Feb. 23, 2023 Unstable
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:12: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:15: '' : #version directive missing

[W] Shader shaders/default.vert | shaders/fog.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:13: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:12: '' : #version directive missing

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/default.vert | shaders/unitarmor.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:12: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:12: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:19: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:14: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:14: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:17: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:17: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:14: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/caustics.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:14: '' : #version directive missing

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/clouds.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[I] [Mindustry] Version: 142
[I] Loaded mod 'schematics-pack' in 7.7781ms
[I] Loaded mod 'NeonNights 2' in 18.9524ms
[I] [schematics-pack/main.js]: SCHEMATICS-PACK Settings contains settingsKey: 'scheme-pack-v'
[I] [schematics-pack/main.js]: SCHEMATICS-PACK previous version:1, current version:1
[I] [schematics-pack/main.js]: SCHEMATICS-PACK loaded 0 deleted schematics
[I] Time to initialize modded scripts: 1498.6268
[W] No icon found for glyph:  (59443)
[W] The icon stuff took 192.3064
[I] Total time to load: 26570ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
WARNING: 0:8: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_bloom.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:10: '' : #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_threshold.frag:
Vertex shader
WARNING: 0:7: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/alpha_gaussian.frag:
Vertex shader
WARNING: 0:8: '' : #version directive missing

Fragment shader:
WARNING: 0:11: '' : #version directive missing

[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Initialized Discord rich presence.
[I] Fetched 42 community servers.

pls fix this has been so painful :(

**Comment by buthed010203** [comment]
Are you streaming on discord by chance?

**Comment by buthed010203** [comment]
If anything this would actually be a vanilla bug
