### ISSUE TITLE
[Bug] When press F

### ISSUE THREAD

**Issue by Linnnnnna** [mindustry-antigrief/mindustry-client#154]
[b6f819b, Apr. 6, 2023 Unstable](https://github.com/mindustry-antigrief/mindustry-client-v7-builds/releases/tag/1392)

https://user-images.githubusercontent.com/63439268/230248639-ed269688-f4f5-49c9-bf9d-8ad48a878781.mp4

**Comment by buthed010203** [comment]
Aware of this but not sure who caused it and cant be bothered to go find it right now

**Comment by Linnnnnna** [comment]
![e](https://user-images.githubusercontent.com/63439268/230296887-ea4278f0-a66e-4836-abb8-02abb8dfff10.gif)

**Comment by dmgnr** [comment]
it happens to me too

**Comment by buthed010203** [comment]
This was fixed like a week ago

**Comment by Linnnnnna** [comment]
![ESSQBG8KNP5Z4D D)8W{RT](https://user-images.githubusercontent.com/63439268/233836169-4b94ceba-06e3-40e8-8984-60428b461699.gif)
