### ISSUE TITLE
[Bug] can't hear modded sfx

### ISSUE THREAD

**Issue by rylid-umil** [mindustry-antigrief/mindustry-client#164]
### What happened?

I can't hear any custom sfx from mods. I'm wondering if this client has anything to do with the problem.

### Relevant log output

```shell
There isn't any logs for me to show.
```

**Comment by buthed010203** [comment]
What mods are you using?

**Comment by rylid-umil** [comment]
testing utils, modded admin button, new console, time control

**Comment by buthed010203** [comment]
Which mod has sfx that don't play? As far as I can tell, new console, time control and testing utilities don't have custom sounds, couldn't find whatever this modded admin button mod is though.

**Comment by rylid-umil** [comment]
modded admin button is admin button but i made it say "ohio" instead. anyway, it seems to happen with every mod, ca-mod, m y mod (new units). can't try exogenesis tho (carbon freeze error maybe bcuz of the client). it waws working in v6 but now it doesn't work.

**Comment by buthed010203** [comment]
Link any broken mod so i can test it please

**Comment by rylid-umil** [comment]
so first, rylid-umil/new-units i think, and then Chaoticans-mindustry-modding-team/ca-mod

actually, new units doesn't ahve any broken sounds, it used to tho so not rylid-umil/new-units

**Comment by rylid-umil** [comment]
BRUH

**Comment by rylid-umil** [comment]
i guess it will never be fixed.

**Comment by buthed010203** [comment]
This may have actually been fixed the other day, try deleting and redownloading the mods

**Comment by rylid-umil** [comment]
didnt really work, couldn't hear the sfx

**Comment by buthed010203** [comment]
Works fine for me.
