### ISSUE TITLE
Typo for Show Ally Turrets

### ISSUE THREAD

**Issue by stoltzld** [mindustry-antigrief/mindustry-client#179]
### What happened?

I tried enabling showing ally turrets by pressing Shift+\` like it shows in the status area.  It turns out the actual hotkey that works is Alt+\`.

![image](https://github.com/mindustry-antigrief/mindustry-client/assets/5799151/c7db3795-438b-4b8e-80bc-8bb99116973c)

**Comment by BalaM314** [comment]
oops
