### ISSUE TITLE
wheres thw wiki?

### ISSUE THREAD

**Issue by Djspac3** [mindustry-antigrief/mindustry-client#183]
### What happened?

realy tho

**Comment by Djspac3** [comment]
dang it i didnt want the bug lable

**Comment by Djspac3** [comment]
DANG IT
im with github i need to stop

**Comment by Darthscion55** [comment]
Almost everything you need to know about foos is in the settings, or in the keybind menu. Or other players know some things too. Even to this day after close to a year of using, I still re read the user guide and relearn something.

**Comment by buthed010203** [comment]
There is no wiki. The in game feature list is the closest thing to that we have currently

**Comment by Djspac3** [comment]
k
