### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by Djspac3** [mindustry-antigrief/mindustry-client#184]
I understand that the installer might not work with mobile but why do I need to makes a beta thing?
Also I'm new to github hii

**Comment by Darthscion55** [comment]
> I understand that the installer might not work with mobile but why do I need to makes a beta thing? Also I'm new to github hii

What? No. Foos will NOT work on mobile. 
What are you talking about a beta?

**Comment by buthed010203** [comment]
The client doesnt run on mobile

**Comment by Djspac3** [comment]
oh

**Comment by Djspac3** [comment]
@Darthscion55 in building there's
Tho sorry for bad copy) :
Android
Install the Android SDK [here.](https://developer.android.com/studio#command-tools) Make sure you're downloading the "Command line tools only", as Android Studio is not required.
In the unzipped Android SDK folder, find the cmdline-tools directory. Then create a folder inside of it called latest and put all of its contents into the newly created folder.
In the same directory run the command sdkmanager --licenses (or ./sdkmanager --licenses if on linux/mac)
Set the ANDROID_HOME environment variable to point to your unzipped Android SDK directory.
Enable developer mode on your device/emulator. If you are on testing on a phone you can follow [these instructions](https://developer.android.com/studio/command-line/adb#Enabling), otherwise you need to google how to enable your emulator's developer mode specifically.
Run gradlew android:assembleDebug (or ./gradlew if on linux/mac). This will create an unsigned APK in android/build/outputs/apk.
