### ISSUE TITLE
Screen froze while loading into a server with "logic" displaying in the screen

### ISSUE THREAD

**Issue by crackycookie** [mindustry-antigrief/mindustry-client#22]
**Platform**: Windows

**Build**: release build 122, client version: 5.0.3, release: 45

**Issue**: whenever joining a server, if there is a logic in the screen at the beginning, the window froze.

**Steps to reproduce**: simply join a server that has some logic around the core, I've cross checked with the original Anuke built jar, it worked fine

**Link(s) to mod(s) used**: n/a

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
(i was using the jar desktop-release file, unsure which file is required)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by crackycookie** [comment]
Halfway through placing a logic processor with a function to display how many items left in the core, it freezes again.

The code from the logic process is as listed below:
--start of logic code--
set i 0
getlink a i
sensor t a @type
jump 98 equal t @logic-display
jump 98 equal t @memory-cell
jump 98 equal t @message
set m 0
set x 2
sensor itc a @itemCapacity
jump 19 equal m 0
jump 23 equal m 1
jump 27 equal m 2
jump 31 equal m 3
jump 35 equal m 4
jump 39 equal m 5
jump 43 equal m 6
jump 47 equal m 7
jump 51 equal m 8
jump 55 equal m 9
sensor res a @copper
set res1 @copper
draw color 217 157 115 255 0 0
jump 58 always m 2
sensor res a @lead
set res1 @lead
draw color 140 127 169 255 0 0
jump 58 always m 2
sensor res a @metaglass
set res1 @metaglass
draw color 245 245 245 255 0 0
jump 58 always m 2
sensor res a @graphite
set res1 @graphite
draw color 180 200 210 255 0 0
jump 58 always m 2
sensor res a @titanium
set res1 @titanium
draw color 120 180 230 255 0 0
jump 58 always m 2
sensor res a @thorium
set res1 @thorium
draw color 255 150 200 255 0 0
jump 58 always m 2
sensor res a @silicon
set res1 @silicon
draw color 100 100 100 255 0 0
jump 58 always m 2
sensor res a @plastanium
set res1 @plastanium
draw color 200 220 120 255 0 0
jump 58 always m 2
sensor res a @phase-fabric
set res1 @phase-fabric
draw color 245 185 110 255 0 0
jump 58 always m 2
sensor res a @surge-alloy
set res1 @surge-alloy
draw color 245 230 120 255 0 0
op add m m 1
op sub m1 m 1
jump 63 greaterThan m 5
op sub xx x 0
jump 64 always m 4
op sub xx x 75
op div y res itc
op mul y y 48
op add x1 xx 7
op add x2 xx 1
op add x3 xx 2
draw rect x3 31 13 y 0 0
draw color 255 255 255 255 0 0
draw image x1 10 res1 14 0 0
draw lineRect x2 30 14 49 0 0
read ress cell1 m1
write res cell1 m1
jump 80 lessThan ress res
jump 83 greaterThan ress res
draw color 255 255 0 255 90 0
draw poly x1 23 4 5 45 0
jump 82 always ress res
draw color 0 255 0 255 90 0
draw poly x1 24 3 6 90 0
jump 85 always ress res
draw color 255 0 0 255 90 0
draw poly x1 24 3 6 270 0
op add x x 15
jump 90 lessThanEq m 5
jump 94 greaterThan m 5
jump 8 lessThan m 10
jump 98 always m 1
jump 93 lessThanEq m 4
drawflush display1
draw clear 0 0 0 0 0 0
jump 88 always m 1
jump 97 lessThanEq m 9
drawflush display2
draw clear 0 0 0 0 0 0
jump 88 always m 10
op add i i 1
print "Resources-in-the-core graph "
print "[yellow]v1.4[white]"
print "\nCreated by "
print "frog"
print "\n"
print "frog"
print "core. Thats all. [sky]0w0"
printflush message1
jump 1 lessThan i @links
--end of logic code--

![image](https://user-images.githubusercontent.com/12483188/103331675-18c78200-4abb-11eb-9920-72b1e15960d3.png)
This was the setup of the logic & displays, captured in Anuke built client.

**Update test, most likely is the logic display issue, as I've tried to copy the code from logic processor to a micro processor, it worked fine without a logic display.

**Comment by buthed010203** [comment]
Couldn't reproduce it.

**Comment by crackycookie** [comment]
Oh, there's another problem other than that, even I tried to start campaign mode, it froze...I guess it's my machine problem then...
