### ISSUE TITLE
[Suggestion] a script console 

### ISSUE THREAD

**Issue by Djspac3** [mindustry-antigrief/mindustry-client#225]
I'm thinking about getting a new console since the current console mod is outdated and the creator doesn't seem to be updating it.
 The `!js` command isn't great because it's just a one-liner. 
If a new console is in the works, it would be awesome to have info on the changes made by running JavaScript.

Also, I know I should use Discord, but I don't have an account and I'm not planning to make one, sorry. Thanks!

**Comment by JasonP01** [comment]
You can use multiple "lines" with !js if you seperate commands with ; it also has the added benefit of preserving all data like vars issued in that "one liner"

**Comment by kennarddh** [comment]
you are so quick

**Comment by JasonP01** [comment]
*it would only remember vars for that line, any new messages sent would be unique as well unless you issue a const var which is permanent until you close the game

**Comment by kennarddh** [comment]
It's better to use console instead of `!js` command because chat message has length limit.

**Comment by JasonP01** [comment]
No

**Comment by JasonP01** [comment]
If you start a msg with !js there is no text limit (there is but iirc its set to 1k chars)

**Comment by kennarddh** [comment]
> *it would only remember vars for that line, any new messages sent would be unique as well unless you issue a const var which is permanent until you close the game

What? Iirc they share the same context for a game

**Comment by kennarddh** [comment]
> If you start a msg with !js there is no text limit (there is but iirc its set to 1k chars)

That's short for code

**Comment by JasonP01** [comment]
Im too lazy to link the line, just search for "!js" in this repo and see

**Comment by kennarddh** [comment]
Just try no need to find the code

**Comment by JasonP01** [comment]
> What? Iirc they share the same context for a game

The game has no memory of anything that transpired after its closed, most things arent saved into appdata, the game redeclares most const vars on startup and the like. You cant permanently declare a var that persists game closure unless you compile it into the game itself

**Comment by JasonP01** [comment]
Most yapping in an issue ever, besides your one issue in toast repo with that one dude

**Comment by JasonP01** [comment]
Rip, i hope we didnt yap so hard bro had to close the issue

**Comment by TheEt1234** [comment]
just use the new console mod

**Comment by Djspac3** [comment]
It's BASICLY discontinued the dev DOESNT want to EVEN TOUTCH IT
