### ISSUE TITLE
mod errors

### ISSUE THREAD

**Issue by An0yim0us666** [mindustry-antigrief/mindustry-client#29]
some mods get content errors and crashes the game instantly on foo's but not on the normal version... is it fixable?

**Comment by buthed010203** [comment]
Cant fix it without a log

**Comment by An0yim0us666** [comment]
here is the crash log
[crash-report.txt](https://github.com/mindustry-antigrief/mindustry-client-v6/files/6038429/crash-report.txt)

**Comment by buthed010203** [comment]
Fixed this yesterday, will merge it when I get home.
