### ISSUE TITLE
PMs

### ISSUE THREAD

**Issue by UltraBlackLinux** [mindustry-antigrief/mindustry-client#3]
I Thought it would fit here, since Anuken will propably never add pms and it's pretty much a clientside thing.
I hope it has a chance here.
Thanks!

**Comment by buthed010203** [comment]
Encrypted chat messages were a thing in the v5 client, foo will probably merge those into v6 some day.

**Comment by Darklord2996** [comment]
PMS ooo time to spamm feature requests

**Comment by buthed010203** [comment]
Exists now
