### ISSUE TITLE
[Suggestion] Save file editor

### ISSUE THREAD

**Issue by UltraBlackLinux** [mindustry-antigrief/mindustry-client#50]
Hey there,
I'd love to see some features regarding messing with campaign save files.
My Ideas: (re)set waves, force sector attack, reset sector save file, sector backup/restore, force unlock sector - Just utilities like this.
Thanks!

**Comment by buthed010203** [comment]
This can all be done with the `!js` command

**Comment by UltraBlackLinux** [comment]
> This can all be done with the `!js` command

If one knew, how.
JS bad.
