### ISSUE TITLE
Extension for block logs: Display destroyed blocks

### ISSUE THREAD

**Issue by UltraBlackLinux** [mindustry-antigrief/mindustry-client#6]
Make destroyed blocks show up in the history, so you can rebuild them ;)

**Comment by blahblahbloopster** [comment]
Destroyed blocks show up in the tile logs (though not in the last accessed area).

**Comment by UltraBlackLinux** [comment]
The tile logs only focus on showing the person who placed the block - it seems like this client only records what's happening, so blocks with no pre-existing logs (you joined later) have no entry in the tile logs :|

**Comment by blahblahbloopster** [comment]
Without serverside cooperation the client can't see what happened before it joined.

**Comment by UltraBlackLinux** [comment]
so it actually recieves the info from the server?
I mean that's kinda a dumb question, but I thought, the server doesn't send you the info in advance for old stuff

**Comment by blahblahbloopster** [comment]
No, it just records whenever a block is placed, broken, configured, picked up, or dropped.

**Comment by UltraBlackLinux** [comment]
So then why not make the client pick up all blocks on join to have them registered and able to be seen in the logs?

**Comment by blahblahbloopster** [comment]
What do you mean pick up?

**Comment by UltraBlackLinux** [comment]
Register them - scan every block.

**Comment by blahblahbloopster** [comment]
It doesn't really need to do that, the server sends an event whenever a block is placed/broken/configured/picked up as a payload, etc so it doesn't really need to register anything.  However, it can't see what happens before it joins because the server only sends the events when the interactions happen.

**Comment by UltraBlackLinux** [comment]
But how does the client pick up the map then? I mean if it was all interaction based, the map would slowly build up, based on players changing blocks and stuff - can't you get your block infos from that?

**Comment by buthed010203** [comment]
this was added ~3 years ago
