### ISSUE TITLE
[SUGGESTION] Please add an undo function for deletes

### ISSUE THREAD

**Issue by JD-The-65th** [mindustry-antigrief/mindustry-client#65]
Hello reader.
From transitioning over from Mobile Mindustry to PC Mindustry, I find it really easy to accidentally grief when holding Right Mouse Button.
Please add some type of undo function so that if you accidentally delete something, you can restore it.

**Comment by buthed010203** [comment]
This would be a nice thing to have, I should look into a way of doing this efficiently. For now you can just toggle building on and off with E (or even enable the thing that disables it when the queue is empty) I suppose.

**Comment by bend-n** [comment]
i would like undos for placement, and for placement of schematics, too. please.

**Comment by buthed010203** [comment]
Has existed for a good while
