### ISSUE TITLE
Clickable chat links

### ISSUE THREAD

**Issue by UltraBlackLinux** [mindustry-antigrief/mindustry-client#7]
Would be cool, if this was actually a Link ;)
![Screenshot_20201116_184307](https://user-images.githubusercontent.com/62404294/99288231-94d37680-283b-11eb-882d-1cec526503ec.png)

Sry for the issue spam - but I see alot of potential in this project!

**Comment by buthed010203** [comment]
You should probably join the discord so ppl can discus these additions easier https://discord.gg/jnqvp6J

**Comment by buthed010203** [comment]
this would require placing buttons in the chat which would take a massive amount of effort for something so simple
