### ISSUE TITLE
Chat formatting

### ISSUE THREAD

**Issue by UltraBlackLinux** [mindustry-antigrief/mindustry-client#8]
One of BD's most known plugins is a chat formatting plugin - I'd love to see such a feature: At least "Varied", because it's such an ironic thing. (Hello > HeLlO)
![Screenshot_20201116_184843](https://user-images.githubusercontent.com/62404294/99288742-5b4f3b00-283c-11eb-8807-e3c3926978e8.png)

**Comment by USMP-lancer** [comment]
sink

**Comment by USMP-lancer** [comment]
@buthed010203 close this crusty issue

**Comment by buthed010203** [comment]
I dont see this happening any time soon
